name: Upload database

# This GitHub Actions workflow checkouts the PostGIS database dump
# pre-populated on @whkchow's computer and upload it as release assets
# (for a tagged release) on GitHub

on:
  push:
#   branches:
#     - '**'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true

concurrency: prevent-race-condition

jobs:
  upload-opendrr-database:
    runs-on: ubuntu-22.04
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Make more room by deleting unused software
        if: ${{ github.event_name != 'schedule' }}
        run: |
          set -x
          df -h
          du -csh /usr/share/dotnet
          du -csh /usr/local/lib/android
          du -csh /opt/ghc || true
          du -csh /usr/share/swift || true
          du -csh /usr/local/graalvm || true
          sudo eatmydata rm -rf /usr/share/dotnet       # 24.1 GB / 468 MiB?
          sudo eatmydata rm -rf /usr/local/lib/android  # 11.3 GB / 14 GiB
          sudo eatmydata rm -rf /opt/ghc || true        #  1.8 GB / Non-existent
          sudo eatmydata rm -rf /usr/share/swift || true #  1.3 GB
          sudo eatmydata rm -rf /usr/local/graalvm || true #  1.0 GB
          df -h

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 7-zip
        run: |
          sudo eatmydata apt update
          sudo apt install -y 7zip

      - name: Extract database dump from 7z archive
        run: |
          eatmydata 7zz x *.7z.001

      - name: Calculate checksum of database dump
        run: |
          set -x
          sha256sum -b *.sql > $(echo *.sql).sha256sum

      - name: Free up more space by removing Git objects and 7z archive
        run: |
          set -x
          df -h
          du -csh .git/objects
          du -csh *.7z.*
          rm -rf .git/objects
          rm -f *.7z.*
          df -h

#     - name: "Upload database dump as GitHub artifact"
#       uses: actions/upload-artifact@v3
#       if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
#       with:
#         name: opendrr-boundaries-sql
#         path: |
#           *.sql
#           *.sql.*sum
#         if-no-files-found: error

      - name: Split database dump into 2GB chunks (for tagged release)
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        run: |
          set -x
          eatmydata split -b 2GB -d --verbose *.sql $(echo *.sql).
          for i in $(echo *.sql).[0-9][0-9]; do
            sha256sum -b "${i}" >> $(echo *.sql).sha256sum
          done

      - name: "Upload database dump as GitHub release asset (for tagged release)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          files: |
            *.sql.[0-9][0-9]
            *.sql.sha256sum
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload database dump as release assets using xresloader/upload-to-github-release@v1"
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.sql.[0-9][0-9];*.sha256sum"
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || '' }}
          tags: true
          draft: false
